define(
    [
        'dispatcher/AppDispatcher',
        'constants/AppConstants',
        'lib/events',
        'lodash'
    ],  
    function(
        AppDispatcher,
        AppConstants,
        Events,
    _
    ){
        var 
    }
);